# Generated by Django 2.0.7 on 2018-07-18 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=11)),
                ('unidades', models.IntegerField(default=1)),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=11)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Categoria')),
                ('empresas', models.ManyToManyField(to='vendas.Empresa')),
            ],
        ),
    ]
