# Generated by Django 2.0.7 on 2018-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='document',
            field=models.FileField(default='', upload_to='assets/file/'),
        ),
    ]
